CACHESTER_SOURCE_VERSION = \
  "$(shell git log --pretty=format:'%ad %h%d' --abbrev-commit --date=short -1)"

CACHESTER_FILE_MAJOR_VERSION = 1
CACHESTER_FILE_MINOR_VERSION = 0

CACHESTER_WIRE_MAJOR_VERSION = 2
CACHESTER_WIRE_MINOR_VERSION = 0
