#!/bin/sh
# Copyright (c)2014-2017 Peak6 Investments, LP.  All rights reserved.
# Use of this source code is governed by the LICENSE file.

case x"$1" in
	xstart)
		exec_dir=`dirname "$0"`
		scr_dir=`dirname "$0"`

		if test x"$exec_dir" = x
		then
			exec_dir=`dirname \`which \\\`basename "$0"\\\`\``
		else
			pwdold=`pwd`
			cd "$exec_dir"
			exec_dir=`pwd`
			cd "$pwdold"
		fi

		exec_dir="$exec_dir"/../bin

		LD_LIBRARY_PATH="$exec_dir:$LD_LIBRARY_PATH"
		export LD_LIBRARY_PATH

		case x`uname` in
			xLinux) echo 0x2F > /proc/$$/coredump_filter ;;
		esac

		$scr_dir/pubctl stop
		exec "$exec_dir"/pubmux "$@" ;;
	xstop)
		u="$LOGNAME"
		test -z "$u" && u="$USER"
		killall -q -u "$u" pubmux &&
			sleep 2 &&
				killall -q -u "$u" -9 pubmux ;;
	*)
		echo "Syntax error: $0 start|stop" >&2
		exit 1
esac
