#! /bin/sh

dir="${1?Syntax: $0 LOG-DIRECTORY [LOG-DIRECTORY ...]}"
code=0
today=$(date +"%Y-%m-%d")

for dir in $*
do
	files=`find "$dir" -name '*.log_????-??-??'`
	stashfiles=`find "$dir" -name 'stash.log'`
	new_code=$?
	if test x$new_code = x0
	then
		if test x"$files" != x
		then
			gzip $files
			new_code=$?
			test x$code = x0 && code=$new_code
		fi

		if test x"$stashfiles" != x
		then
		    gzip $stashfiles
		    mv $dir/stash.log.gz $dir/stash.log_${today}.gz
		    test x$code = x0 && code=$new_code
		fi
	else
		test x$code = x0 && code=$new_code
	fi
done

exit $code
