#! /bin/sh

dir="${1?Syntax: $0 LOG-DIRECTORY [LOG-DIRECTORY ...]}"

for dir in $*
do
	if test -d "$dir"
	then
		files=`find "$dir" -name '*.log_????-??-??'`
		test x"$files" = x || gzip $files
	else
		echo "$0: error: directory $dir does not exist" >&2
		exit 2
	fi
done
