#! /bin/sh

log_dir="/plogs/pubmgr"
mkdir -p "$log_dir" || exit 1

exec_dir=`dirname "$0"`
if test x"$exec_dir" = x
then
	exec_dir=`dirname \`which \\\`basename "$0"\\\`\``
else
	pwdold=`pwd`
	cd "$exec_dir"
	exec_dir=`pwd`
	cd "$pwdold"
fi
$exec_dir/stopPubMgr
exec_dir="$exec_dir"/../bin

LD_LIBRARY_PATH="${exec_dir}:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH

case x`uname` in
	xLinux) echo 0x2F > /proc/$$/coredump_filter ;;
esac

copy_stats=0
for i in "$@"
do
	case x"$i" in
		x-stats=) copy_stats=1 ; break ;;
	esac
done

date=`date +'%Y-%m-%d'`
log="$log_dir"/server.log_"$date"

if test x"$copy_stats" = x1
then
	stat="$log_dir"/stats.log_"$date"
	"$exec_dir"/pubmgr "$@" >> "$stat" 2>> "$log" &
else
	"$exec_dir"/pubmgr "$@" >> "$log" 2>&1 &
fi
